project:
  type: website
  output-dir: docs

website:
  title: "AtkinsLab @ VCU"
  navbar:
    logo: images/fire1.jpg
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: tools.qmd
        text: Tools
      - href: data.qmd
        text: Data
      - href: opportunities.qmd
        text: Opportunities

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual